# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumah_sakit', '0001_initial'),
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asuransi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('url_website', models.CharField(max_length=400, unique=True)),
                ('dokumen', models.FileField(blank=True, upload_to='dokumen_asuransi')),
                ('foto_profil', models.ImageField(blank=True, upload_to='foto_profil_asuransi')),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('status_validasi', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request')], default='request', max_length=50)),
                ('waktu_validasi', models.DateTimeField(blank=True, null=True)),
                ('administrator', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asuransis', to='utama.Administrator')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asuransis', to='utama.Akun')),
            ],
        ),
        migrations.CreateModel(
            name='HubunganRumahSakitAsuransi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokumen', models.FileField(blank=True, upload_to='dokumen_hubungan_rumah_sakit_asuransi')),
                ('status_validasi_rumah_sakit', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request')], default='request', max_length=50)),
                ('status_validasi_administrator', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request')], default='request', max_length=50)),
                ('waktu_validasi', models.DateTimeField(blank=True, null=True)),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubungan_rumah_sakit_asuransis', to='utama.Administrator')),
                ('asuransi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubungan_rumah_sakit_asuransis', to='asuransi.Asuransi')),
                ('rumah_sakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubungan_rumah_sakit_asuransis', to='rumah_sakit.RumahSakit')),
            ],
        ),
    ]
