# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuransi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuransi',
            name='url_website',
            field=models.CharField(max_length=400),
        ),
    ]
