# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumah_sakit', '0001_initial'),
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_review', models.ImageField(blank=True, upload_to='foto_review')),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('golongan_darah', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=4)),
                ('provinsi', models.CharField(max_length=100, null=True)),
                ('kabupaten_kota', models.CharField(max_length=100, null=True)),
                ('kecamatan', models.CharField(max_length=100, null=True)),
                ('kelurahan', models.CharField(max_length=100, null=True)),
                ('rt_rw', models.CharField(max_length=100, null=True)),
                ('kode_pos', models.CharField(max_length=40, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='jenis', max_length=8)),
                ('nomor_telepon', models.CharField(max_length=20, null=True)),
                ('foto_profil', models.ImageField(blank=True, upload_to='foto_profil_pengunjung')),
                ('status_validasi', models.CharField(choices=[('request', 'Request'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='request', max_length=30)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengunjungs', to='utama.Akun')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_review', models.TextField()),
                ('waktu_stamp', models.DateTimeField(auto_now_add=True)),
                ('waktu_validasi', models.DateTimeField(blank=True, null=True)),
                ('data_lokasi_pengunjung_lintang', models.CharField(default='', max_length=300, null=True)),
                ('data_lokasi_pengunjung_bujur', models.CharField(default='', max_length=300, null=True)),
                ('status_validasi', models.CharField(choices=[('rejected', 'Rejected'), ('validated', 'Validated'), ('request', 'Request'), ('rejected_by_system', 'Rejected By System')], default='request', max_length=50)),
                ('rating', models.PositiveIntegerField()),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pengunjung.Pengunjung')),
                ('rumah_sakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rumah_sakit.RumahSakit')),
            ],
        ),
        migrations.AddField(
            model_name='fotoreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_reviews', to='pengunjung.Review'),
        ),
    ]
