# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='pria', max_length=10)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('foto_profil', models.ImageField(blank=True, upload_to='foto_profil_administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pengunjung', 'Pengunjung'), ('rumah_sakit', 'Rumah Sakit'), ('asuransi', 'Asuransi'), ('administrator', 'Administrator')], max_length=100)),
                ('waktu_registrasi', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, unique=True)),
                ('isi', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('foto_berita', models.ImageField(blank=True, upload_to='foto_berita')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beritas', to='utama.Administrator')),
            ],
            options={
                'ordering': ('-waktu',),
            },
        ),
        migrations.AddField(
            model_name='administrator',
            name='akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='utama.Akun'),
        ),
    ]
