# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nomor_telepon', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FasilitasRumahSakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_fasilitas', models.CharField(max_length=200)),
                ('jumlah', models.PositiveIntegerField()),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FotoRumahSakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_rumah_sakit', models.ImageField(blank=True, upload_to='foto_rumah_sakit')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalDokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senin_masuk', models.TimeField(blank=True, null=True)),
                ('senin_keluar', models.TimeField(blank=True, null=True)),
                ('selasa_masuk', models.TimeField(blank=True, null=True)),
                ('selasa_keluar', models.TimeField(blank=True, null=True)),
                ('rabu_masuk', models.TimeField(blank=True, null=True)),
                ('rabu_keluar', models.TimeField(blank=True, null=True)),
                ('kamis_masuk', models.TimeField(blank=True, null=True)),
                ('kamis_keluar', models.TimeField(blank=True, null=True)),
                ('jumat_masuk', models.TimeField(blank=True, null=True)),
                ('jumat_keluar', models.TimeField(blank=True, null=True)),
                ('sabtu_masuk', models.TimeField(blank=True, null=True)),
                ('sabtu_keluar', models.TimeField(blank=True, null=True)),
                ('minggu_masuk', models.TimeField(blank=True, null=True)),
                ('minggu_keluar', models.TimeField(blank=True, null=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_dokters', to='rumah_sakit.Dokter')),
            ],
        ),
        migrations.CreateModel(
            name='JenisFasilitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasilitas', models.CharField(max_length=300)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gejala', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto_profil', models.ImageField(blank=True, upload_to='foto_profil_rumah_sakit')),
                ('dokumen', models.FileField(blank=True, upload_to='dokumen_rumah_sakit')),
                ('url_website', models.CharField(max_length=400, null=True, unique=True)),
                ('provinsi', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=100, null=True)),
                ('kode_pos', models.CharField(max_length=100, null=True)),
                ('fax', models.CharField(max_length=40, null=True)),
                ('nomor_telepon', models.CharField(max_length=20, null=True)),
                ('lokasi_rumah_sakit_lintang', models.CharField(default='', max_length=100, null=True)),
                ('lokasi_rumah_sakit_bujur', models.CharField(default='', max_length=100, null=True)),
                ('status_validasi', models.CharField(choices=[('request', 'Request'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='request', max_length=20)),
                ('waktu_validasi', models.DateField(blank=True, null=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rumah_sakits', to='utama.Administrator')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Akun')),
            ],
        ),
        migrations.CreateModel(
            name='Spesialis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_spesialis', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='penyakit',
            name='spesialis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penyakits', to='rumah_sakit.Spesialis'),
        ),
        migrations.AddField(
            model_name='fotorumahsakit',
            name='rumah_sakit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_rumah_sakits', to='rumah_sakit.RumahSakit'),
        ),
        migrations.AddField(
            model_name='fasilitasrumahsakit',
            name='jenis_fasilitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas_rumah_sakits', to='rumah_sakit.JenisFasilitas'),
        ),
        migrations.AddField(
            model_name='fasilitasrumahsakit',
            name='rumah_sakit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas_rumah_sakits', to='rumah_sakit.RumahSakit'),
        ),
        migrations.AddField(
            model_name='dokter',
            name='rumah_sakit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokters', to='rumah_sakit.RumahSakit'),
        ),
        migrations.AddField(
            model_name='dokter',
            name='spesialis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokters', to='rumah_sakit.Spesialis'),
        ),
    ]
